### ISSUE TITLE
Plugin to clean URLs

### ISSUE THREAD

**Issue by wooorm** [rehypejs/ideas#7]
Something like https://github.com/Smile4ever/Neat-URL

Would be nice to run this on user-generated content, e.g., on the [unified explore page](https://unifiedjs.com/explore/) where we render readmes, to remove tracking for our users.

**Comment by ericdmoore** [comment]
@wooorm Did you think this might be: 
- removing all query params? 
- removing only query params that match a "removal list"?
- removing all query params, except for domains that are on a "leave alone list"?

**Comment by wooorm** [comment]
I was thinking of b)! to remove pesky analytics and such. Although, that might come with c) too.
a) would be easier, but probably breaks stuff because too much is removed? 🤔

**Comment by ericdmoore** [comment]
## Background 
I was thinking of using this as an exercise in building a plugin. Just wanted some direction on implementation ideas if you had given it any thought.

## Overview
I agree on using both a "keep" and "remove" list approach. Since the "bad actors list" can grow without limits it suggests to me to first start with the "leave alone domains" list given its seeming higher level of stability. This list likely starts with things like the url patterns from `shields.io` etc

removal list might start with:
- `utm_source`
- `utm_medium` 
- `utm_campaign` 
- `utm_term` 
- `utm_content` 
- plus other easily researched query string based tracking params

Would you recommend adding anything to the `vfile.messages` or `vfile.info` for "could not clean up this link" messages? I am still getting familiarized with the culturally appropriate spot to put something like that.

**Comment by wooorm** [comment]
Nice: fun, and useful!

If I’d do it, I’d look at neat-url linked above. E.g., [they seem to have the patterns](https://github.com/Smile4ever/Neat-URL/blob/master/data/default-params-by-category.json)! Interestingly, it seems they’re not checking domains, just stripping params?

I don’t think you should add messages to vfile by default. My use case was to run it on a ton of user-generated content.
But you could do it, maybe optionally? But then I’m wondering: what use is the message that some GA stuff was removed? Do you expect false-positives?

**Comment by wooorm** [comment]
Oh wait, I guess their `@` syntax includes optionally a domain: `cvid@bing.com` removes that on bing addresses!

**Comment by ericdmoore** [comment]
Thanks. Great nudge.

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @wooorm !
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/rehypejs/rehype/discussions/categories/ideas will be the home for ideas going forward.
